name: ADMIN TEST CI&CD setup

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn' 

      - name: Install yarn dependencies
        run: yarn install

      - name: Run build task
        run: yarn build:test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_KIN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_KIN }}
          aws-region: ${{ secrets.AWS_REGION_KIN}}

      - name: Deploy to S3
        run: aws s3 sync build s3://${{ secrets.S3_BUCKET_TEST }} --delete
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{
          secrets.CLOUDFRONT_DISTRIBUTION_ID_TEST }} --paths "/*"

      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Admin-TEST deployed succesfully
          notification-color: 28a745
          timezone: Asia/Kolkata
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        if: failure()        
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Admin-TEST deployment failed
          notification-color: dc3545 
          timezone: Asia/Kolkata           