name: ADMIN TEST CI&CD setup

on:
  push:
    tags:
      - "*"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
        with:  
          node-version: '14.x' 
          cache: 'yarn'  

      - name: Install yarn dependencies
        run: yarn install

      - name: Run build task
        run:  yarn build:test
      # - name: deploy to server
      #   uses: AEnterprise/rsync-deploy@v1.0
      #   env:
      #     DEPLOY_KEY: ${{ secrets.KINERGY_PEM }}
      #     ARGS: "-e -c -r --delete"
      #     SERVER_PORT: 22
      #     FOLDER: build/*
      #     SERVER_IP: ${{ secrets.KINERGY_IP }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     SERVER_DESTINATION: ${{ secrets.DESTINATION_TEST }}
          
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: build/*
          remote_path: ${{ secrets.DESTINATION_TEST }}
          remote_host: ${{ secrets.KINERGY_IP }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KINERGY_PEM }}  

