name: Admin UAT CI&CD setup
on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
        with:  
          node-version: '16.x' 
          cache: 'yarn'  

      - name: Install yarn dependencies
        run: yarn install

      - name: Run build task
        run:  yarn build:uat
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_KIN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_KIN}}
          aws-region: ${{ secrets.AWS_REGION_KIN }}

      - name: Deploy to S3
        run: aws s3 sync build s3://${{ secrets.S3_BUCKET_UAT }} --delete
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{
          secrets.CLOUDFRONT_DISTRIBUTION_ID_UAT }} --paths "/*"