name: Customer UAT CI&CD setup

on:
  release:
    types: [published]

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
        with:  
          node-version: '18.x' 
          cache: 'yarn'  

      - name: Install yarn dependencies
        run: yarn install
      - name: Run build task
        run:  yarn build:uat

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: build/*
          remote_path: ${{ secrets.DESTINATION_UAT }}
          remote_host: ${{ secrets.KINERGY_UAT_IP }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KINERGY_UAT_PEM }}


     